version: '3.8'

services:
  web:
    build:
      context: .
      target: runner
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - yachti-network

  # Add Redis for caching (optional)
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - yachti-network
    volumes:
      - redis-data:/data

networks:
  yachti-network:
    driver: bridge

volumes:
  redis-data: